name: Terraform EKS Infrastructure

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Choose the Terraform action to perform"
        required: true
        default: "apply"
        type: choice
        options:
          - apply
          - destroy
      environment:
        description: "Choose the environment (dev or prod)"
        required: true
        default: "dev"
        type: string

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      TF_LOG: "INFO"
      AWS_REGION: "us-east-1"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
        
    - name: Lint and Fix Terraform Files
      run: |
        terraform fmt -check -recursive || {
          echo "Formatting issues detected. Fixing..."
          terraform fmt -recursive
          }
      working-directory: eks-cluster/env/${{ github.event.inputs.environment }}
      
    - name: Terraform Init
      run: terraform init
      working-directory: eks-cluster/env/${{ github.event.inputs.environment }}

    - name: Terraform Plan
      run: terraform plan -out=tfplan
      working-directory: eks-cluster/env/${{ github.event.inputs.environment }}

    - name: Terraform Apply
      if: ${{ github.event.inputs.action == 'apply' }}
      run: terraform apply -auto-approve tfplan
      working-directory: eks-cluster/env/${{ github.event.inputs.environment }}

    - name: Terraform Destroy
      if: ${{ github.event.inputs.action == 'destroy' }}
      run: terraform destroy -auto-approve
      working-directory: eks-cluster/env/${{ github.event.inputs.environment }}
