name: Terraform EKS Infrastructure

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Choose the Terraform action to perform"
        required: true
        default: "apply"
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      TF_LOG: "INFO"
      AWS_REGION: "us-east-1"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Determine Environment
      id: set-env
      run: |
        if [[ "${GITHUB_REF##*/}" == "dev" ]]; then
          echo "ENV_FOLDER=dev" >> $GITHUB_ENV
        elif [[ "${GITHUB_REF##*/}" == "prod" ]]; then
          echo "ENV_FOLDER=prod" >> $GITHUB_ENV
        else
          echo "Unknown branch: ${GITHUB_REF##*/}. Exiting."
          exit 1
        fi

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Terraform Init
      run: terraform init
      working-directory: eks-cluster/env/${{ env.ENV_FOLDER }}

    - name: Terraform Plan
      run: terraform plan -out=tfplan
      working-directory: eks-cluster/env/${{ env.ENV_FOLDER }}

    - name: Terraform Apply
      if: ${{ github.event.inputs.action == 'apply' }}
      run: terraform apply -auto-approve tfplan
      working-directory: eks-cluster/env/${{ env.ENV_FOLDER }}

    - name: Terraform Destroy
      if: ${{ github.event.inputs.action == 'destroy' }}
      run: terraform destroy -auto-approve
      working-directory: eks-cluster/env/${{ env.ENV_FOLDER }}